### ISSUE TITLE
Problem running your program

### ISSUE THREAD

**Issue by albo94** [emirn/google_sheet_reader_bot#2] opened 2016-08-18 17:43 UTC
Hi,
I'm not a programmer and I'm sorry to annoy you with this problem.
I would like to create a Telegram bot like your so I followed your detailed guide but I had some problems: (this is the message I receive when I run the program)

> **albo94:~/workspace (master) $ node .**
> secon-bot server started...
> Web server started at http://:::8080
> Error: null
> Status code: 400
> Error: null
> Status code: 400

I think (I hope) I've done correctly the first 6 step of your guide. Now I've some doubts about the following steps: I've just written your commands in Cloud9 console...is it right?
These are my results:

> **albo94:~/workspace (master) $ npm install**
> npm WARN package.json google-sheet-bot@1.0.0 No repository field.
> body-parser@1.15.2 node_modules/body-parser
> ├── content-type@1.0.2
> ├── bytes@2.4.0
> ├── depd@1.1.0
> ├── qs@6.2.0
> ├── on-finished@2.3.0 (ee-first@1.1.1)
> ├── raw-body@2.1.7 (unpipe@1.0.0)
> ├── http-errors@1.5.0 (setprototypeof@1.0.1, inherits@2.0.1, statuses@1.3.0)
> ├── iconv-lite@0.4.13
> ├── debug@2.2.0 (ms@0.7.1)
> └── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
> 
> express@4.14.0 node_modules/express
> ├── content-type@1.0.2
> ├── escape-html@1.0.3
> ├── array-flatten@1.1.1
> ├── utils-merge@1.0.0
> ├── cookie-signature@1.0.6
> ├── methods@1.1.2
> ├── merge-descriptors@1.0.1
> ├── encodeurl@1.0.1
> ├── fresh@0.3.0
> ├── cookie@0.3.1
> ├── range-parser@1.2.0
> ├── serve-static@1.11.1
> ├── parseurl@1.3.1
> ├── etag@1.7.0
> ├── content-disposition@0.5.1
> ├── vary@1.1.0
> ├── path-to-regexp@0.1.7
> ├── depd@1.1.0
> ├── qs@6.2.0
> ├── on-finished@2.3.0 (ee-first@1.1.1)
> ├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
> ├── debug@2.2.0 (ms@0.7.1)
> ├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
> ├── send@0.14.1 (destroy@1.0.4, ms@0.7.1, statuses@1.3.0, mime@1.3.4, http-errors@1.5.0)
> ├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
> └── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)
> 
> node-telegram-bot-api@0.21.1 node_modules/node-telegram-bot-api
> ├── file-type@3.8.0
> ├── mime@1.3.4
> ├── debug@2.2.0 (ms@0.7.1)
> └── bluebird@2.10.2
> 
> request@2.74.0 node_modules/request
> ├── tunnel-agent@0.4.3
> ├── aws-sign2@0.6.0
> ├── oauth-sign@0.8.2
> ├── forever-agent@0.6.1
> ├── is-typedarray@1.0.0
> ├── caseless@0.11.0
> ├── stringstream@0.0.5
> ├── aws4@1.4.1
> ├── isstream@0.1.2
> ├── json-stringify-safe@5.0.1
> ├── extend@3.0.0
> ├── tough-cookie@2.3.1
> ├── qs@6.2.1
> ├── node-uuid@1.4.7
> ├── combined-stream@1.0.5 (delayed-stream@1.0.0)
> ├── mime-types@2.1.11 (mime-db@1.23.0)
> ├── form-data@1.0.0-rc4 (async@1.5.2)
> ├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
> ├── bl@1.1.2 (readable-stream@2.0.6)
> ├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.3.0, sshpk@1.9.2)
> └── har-validator@2.0.6 (pinkie-promise@2.0.1, commander@2.9.0, chalk@1.1.3, is-my-json-valid@2.13.1)
> 
> moment-timezone@0.5.5 node_modules/moment-timezone
> └── moment@2.14.1
> **albo94:~/workspace (master) $ git add .**
> **albo94:~/workspace (master) $ git commit -m "initial version"**
> On branch master
> Your branch is up-to-date with 'origin/master'.
> nothing to commit, working directory clean
> **albo94:~/workspace (master) $ git push**
> Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
> Everything up-to-date

I'm sorry for my stupid question
Thank you for your time

Alberto

**Comment by emirn** [comment] 2016-08-18 18:37
Hi Alberto, congrats on making first steps as programmer! Seems like you missing something in the `config.js` file. Make sure that all ' or " have the matching symbol (to close it).

**Comment by albo94** [comment] 2016-08-18 18:45
Thank you emirn for your quick answer!
I've just checked what you asked me but it seems all okay:

> module.exports = {
>  'TelegramProductionURL': 'https://guilizzoni.herokuapp.com',            // do not forget trailing "/" !!
>  'TelegramToken': '12345-sometoken',       // Telegram token
>  'googleSheetKey': 'https://docs.google.com/spreadsheets/d/SOMEKEYHERE/pubhtml',    // the key of the google sheet (should be public!), extract key from the google sheet doc public url
>  "confTimeZone": "Europe/Berlin"       // time zone of the conference in the form like "Europe/Berlin", see http://momentjs.com/timezone/
> }

Thank you again

Alberto

**Comment by emirn** [comment] 2016-08-18 18:55
Alberto, thank you for the code sample.
Important: for security purposes I've edited your reply and changed your google sheet key and Telegram token with sample text.
I would regenerate Telegram bot key anyway to avoid issues with the security (if someone saw your telegram secret key then she/he can use your bot instead of you. You should keep this key (token) private.

Your code seems to be OK except that you should change
`https://guilizzoni.herokuapp.com` to  `https://guilizzoni.herokuapp.com/` (with `/` symbol at the end)

**Comment by emirn** [comment] 2016-08-18 19:09
You may also try this (if you are running the bot on Cloud9):
Change
`bot = new Bot(config.TelegramToken, { polling: true });` 
to this (it will set the webhook callback address to your cloud9 ip address
`
bot = new Bot(config.TelegramToken, { polling: true });
bot.setWebHook("https://" + process.env.IP + ":" + process.env.PORT + "/" + bot.token );
`

**Comment by albo94** [comment] 2016-08-18 19:47
As you said me, I've just corrected:

> https://guilizzoni.herokuapp.com/

and I changed file "bot.js" in this way:

> if(process.env.NODE_ENV === 'production') {
>   bot = new Bot(config.TelegramToken);
>   bot.setWebHook(config.TelegramProductionURL + bot.token);
> }
> else {
>    bot = new Bot(config.TelegramToken, { polling: true }); bot.setWebHook("https://" + process.env.IP + ":" + process.env.PORT + "/" + bot.token ); 
> }

But these are the results in the terminal window:

> Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: bad webhook: Webhook can be set up only on ports 80, 88, 443 or 8443"}
>     at /home/ubuntu/workspace/node_modules/node-telegram-bot-api/src/telegram.js:136:15
>     at tryCatcher (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromises (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
>     at Async._drainQueue (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
>     at processImmediate [as _immediateCallback](timers.js:383:17)
> Unhandled rejection Error: 409 {"ok":false,"error_code":409,"description":"Conflict: terminated by other long poll or web hook"
>     at /home/ubuntu/workspace/node_modules/node-telegram-bot-api/src/telegramPolling.js:72:15
>     at tryCatcher (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromises (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:697:14)
>     at Async._drainQueue (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate](/home/ubuntu/workspace/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
>     at processImmediate [as _immediateCallback](timers.js:383:17)}

**Comment by emirn** [comment] 2016-08-18 19:49
Have you tried to deploy it to Heroku? Cloud9 has the limitations on the ports used to run the node.js app as it is intended for dev purposes only. So please try to deply to Heroku, is it working there?

**Comment by albo94** [comment] 2016-08-18 19:54
I'm sorry but I don't know how to deploy it to Heroku

**Comment by albo94** [comment] 2016-08-19 14:48
Hi,
thank you for all your assistance!
Today I’ve just tried to deploy the app to Heroku. I say you again that I’m not a programmer, so I’ve tried to do these things that I saw on Heroku website:
1. I installed “Heroku toolbelt”
2. I logged in my account
3. in Heroku web page I connected my app “mat-ban” to my repository in Github “albo94/google_sheet_reader_bot”
4. in my repository in Github I copied “config.js.example” into “config.js” and I changed the parameters you explained me in the guide (telegram key, google key,…)
5. I went to Heroku console and I wrote “git add .” , “git commit -am "make it better” and “git push heroku master”
Now I don’t know what else I’ve to do to run my application

Thank you for your time and help

Alberto

**Comment by emirn** [comment] 2016-08-20 14:18
Hi Alberto, great! Deploying to heroku is really next big step!
Seems like you did all things right. Once you called `git push heroku master` it should be deployed and run automatically.
Check the status of the app using the heroku logs command `heroku logs -t` and it will show live logs from your `node.js` app (the telegram bot is just a node.js app that responds to requests from Telegram network).

**Comment by emirn** [comment] 2016-08-20 14:19
Try to run 
`heroku logs -t`
and then try to send something to your bot. So the Telegram bot will talk to your app and you should be able to see errors in the log (will be displayed in the console in live mode)

**Comment by albo94** [comment] 2016-08-20 14:45
Unfortunately I always obtain the same error:

> 2016-08-20T14:43:41.809346+00:00 heroku[router]: at=info method=POST path="/240357515:AAHAre71NZtGulhKW7jXk_Svxk--GSp6tH4" host=mat-ban.herokuapp.com request_id=dcd34792-8c9a-4d2c-8d65-cf4f6bfcb449 fwd="149.154.167.229" dyno=web.1 connect=0ms service=59ms status=200 bytes=196
> 2016-08-20T14:43:41.947157+00:00 app[web.1]: Error: null
> 2016-08-20T14:43:41.947192+00:00 app[web.1]: Status code: 400

**Comment by emirn** [comment] 2016-08-20 15:27
you need to debug your code. stop heroku app.
then run cloud9 app using menu Run - Debug 
Set the breakpoint (click on the left near the line where it should stop)  right after the line with `bot started..`
Then it will stop on this line and you may go line by line using Run - Step Over from menu.

The issue is that it is not clear which line causes this error message (`Error: null`)

**Comment by albo94** [comment] 2016-08-20 15:44
I selected `show debugger at break` and I run it
but I haven't found the line with `bot started` so I didn't set the breakpoint
is `bot started` in "bot.js"?

**Comment by albo94** [comment] 2016-08-20 16:20
Hi Emirn,
I’m sorry but I think I haven’t understood some of your previous steps:
(referring to your initial simple guide)
1. I create Google Sheet with data (OK!)
2. I publish it to web and I obtain a key (OK!)
3. I create an app on Heroku called “ban20”; **now I’ve some doubts:** 1) I just have to create the app and nothing else, or I’ve to connect the app with my repository in Github “albo94/google_sheet_reader_bot”? 2) Do I need to deploy it to Heroku or not? (The first time I’ve done it, I’ve just created the app and nothing else..is it ok?)
4. I create an account in c9.io and I create a Node.js workspace called again “ban20”; now, in the process of creation, I put in an option field called “Clone from Git” the string “git@github.com:albo94/google_sheet_reader_bot.git”…..is it ok?
5. I create a new telegram bot with BotFather and I obtain a telegram key (OK!)
6. in Cloud9 website, I copy config.js.example into config.js and I replace my keys (OK!)
7. in a terminal windows in Cloud9 website, I write these commands: `nam install`, `git add .`, `git commit -m “initial version”`, `git push`
8. always in the same terminal windows (in Cloud9 website), I write the last command `node .`
9. I open the telegram bot and I write Hi

I write you all "my" detailed guide because maybe I haven't understood something and I commit a banal error because it seems strange to me that I've so many problems following your guide.

Thank you again for all your help!

Alberto

**Comment by emirn** [comment] 2016-08-20 16:51
All seems to be right and that is why can't advise any particular thing except placing `debugger` command into the code (like [this](https://spin.atomicobject.com/2015/09/25/debug-node-js/)) so node.js will stop the console where you may type `n` to go line by line and find where it causes the crash.

about Heroku and Cloud9: you may run the app on Cloud9 but it is for development purposes. For production you should deploy to Heroku (it hosts the production server app).

**Comment by emirn** [comment] 2016-08-20 16:53
you don't have to connect Heroku to Github because Heroku itself is the Git. For some developers who store the code in Github this connection makes autosync of the code from Github to Heroku.
Actually you may use Heroku to store the code too using `git` (it just don't have issues, discussion and interface to edit files on web)

**Comment by albo94** [comment] 2016-08-20 17:00
Referring to your second message, I deleted the connection between Github and Heroku and I deployed again to Heroku. When I write `git push heroic master`, the result is:

> error: src refspec master does not match any.
> error: failed to push some refs to 'https://git.heroku.com/ban20.git'

now I try to do what you explained me in the first message
thank you

**Comment by albo94** [comment] 2016-08-20 17:09
now I put the `debugger` in the `bot.js` file and it seems all right (from beginning to end)
I'm so sorry but which file is my source code?

**Comment by emirn** [comment] 2016-08-23 09:39
sorry for delays - need to try to reproduce it! Don't have any ideas - I suggest you to find JS developer who could check your code live.
I've checked the telegram bot which is running on Heroku based on this code and it is all works fine still but maybe something was changed in the npm packages used and so on

**Comment by albo94** [comment] 2016-08-23 17:45
thank you again for all your help and your time
i'll try another way
thanks

alberto

**Closed as completed** 2016-09-11 13:53 UTC
